const assert = require('node:assert/strict')
const fs = require('node:fs/promises')
const os = require('node:os')
const path = require('node:path')
const vm = require('node:vm')
const { test } = require('node:test')
const minify = require('../scripts/minifyReleaseJavaScript.js')

test('release minification preserves globals, module forms, licenses and source hardlinks', async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'min-release-js-'))
  t.after(() => fs.rm(root, { recursive: true, force: true }))
  const stage = path.join(root, 'app')
  await fs.mkdir(path.join(stage, 'node_modules/example'), { recursive: true })
  const source = '/*! @license Example MIT */\n// discard ordinary comment\nvar sharedValue = 41;\nfunction publicFunction () { return sharedValue + 1; }\n'
  await fs.writeFile(path.join(root, 'source.js'), source)
  await fs.link(path.join(root, 'source.js'), path.join(stage, 'classic.js'))
  await fs.writeFile(path.join(stage, 'node_modules/example/index.cjs'), '#!/usr/bin/env node\nmodule.exports = function namedExport () { return 42; };\n', { mode: 0o755 })
  await fs.writeFile(path.join(stage, 'module.mjs'), 'export const answer = 42;\n')
  await fs.writeFile(path.join(stage, 'LICENSE.txt'), 'Example license')
  const sizes = await minify(stage)
  assert.equal(sizes.files, 3)
  assert.ok(sizes.after < sizes.before)
  assert.equal(await fs.readFile(path.join(root, 'source.js'), 'utf8'), source)
  const classic = await fs.readFile(path.join(stage, 'classic.js'), 'utf8')
  assert.match(classic, /@license Example MIT/)
  assert.doesNotMatch(classic, /discard ordinary comment/)
  const context = vm.createContext({})
  vm.runInContext(classic, context)
  assert.equal(vm.runInContext('publicFunction()', context), 42)
  const commonJS = path.join(stage, 'node_modules/example/index.cjs')
  assert.equal(require(commonJS)(), 42)
  assert.equal(require(commonJS).name, 'namedExport')
  assert.match(await fs.readFile(commonJS, 'utf8'), /^#!\/usr\/bin\/env node/)
  assert.equal((await fs.stat(commonJS)).mode & 0o777, 0o755)
  assert.match(await fs.readFile(path.join(stage, 'module.mjs'), 'utf8'), /export const answer=42/)
  assert.equal(await fs.readFile(path.join(stage, 'LICENSE.txt'), 'utf8'), 'Example license')
})

test('invalid JavaScript fails packaging without replacing the invalid file', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'min-release-invalid-'))
  t.after(() => fs.rm(directory, { recursive: true, force: true }))
  const filename = path.join(directory, 'invalid.js')
  await fs.writeFile(filename, 'function {')
  await assert.rejects(minify(directory), /Transform failed/)
  assert.equal(await fs.readFile(filename, 'utf8'), 'function {')
  assert.deepEqual(await fs.readdir(directory), ['invalid.js'])
})

test('already compact JavaScript never grows', async t => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'min-release-compact-'))
  t.after(() => fs.rm(directory, { recursive: true, force: true }))
  const filename = path.join(directory, 'compact.js')
  const source = 'var x=1'
  await fs.writeFile(filename, source)
  assert.deepEqual(await minify(directory), { files: 1, before: source.length, after: source.length })
  assert.equal(await fs.readFile(filename, 'utf8'), source)
})

test('release minification does not follow file or directory symlinks', { skip: process.platform === 'win32' }, async t => {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'min-release-symlink-'))
  t.after(() => fs.rm(root, { recursive: true, force: true }))
  const stage = path.join(root, 'app')
  const outside = path.join(root, 'outside')
  await fs.mkdir(stage)
  await fs.mkdir(outside)
  const source = '// source outside the staged app\nvar untouched = true;\n'
  await fs.writeFile(path.join(outside, 'source.js'), source)
  await fs.symlink(outside, path.join(stage, 'linked-directory'))
  await fs.symlink(path.join(outside, 'source.js'), path.join(stage, 'linked-file.js'))
  assert.deepEqual(await minify(stage), { files: 0, before: 0, after: 0 })
  assert.equal(await fs.readFile(path.join(outside, 'source.js'), 'utf8'), source)
})
